"""Offline event-driven backtesting engine."""

from traderos.backtesting.engine import BacktestEngine
from traderos.backtesting.errors import (
    AccountingError,
    BacktestConfigurationError,
    BacktestError,
    CausalityViolation,
    ExecutionPolicyError,
    InsufficientCash,
    InvalidMarketDataError,
    InvalidOrderError,
    InvalidOrderTransition,
    OrderTimingError,
)
from traderos.backtesting.execution import (
    CommissionModel,
    ExecutionReport,
    ExecutionSimulator,
    FixedSlippageModel,
    QuoteOrFixedSpreadModel,
    ZeroSlippageModel,
)
from traderos.backtesting.metrics import BuyAndHoldBenchmark, calculate_metrics
from traderos.backtesting.models import (
    BacktestConfig,
    BacktestResult,
    CostConfig,
    EquitySnapshot,
    ExecutionPolicy,
    Fill,
    InitialPosition,
    IntrabarAmbiguityPolicy,
    LedgerEntry,
    MissingBarPolicy,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    PerformanceMetrics,
    PositionSnapshot,
    SlippageConfig,
    SpreadConfig,
    StrategyContext,
    TimeInForce,
    TradeRecord,
)
from traderos.backtesting.portfolio import (
    IdentityCurrencyConverter,
    Portfolio,
    StaticCurrencyConverter,
)
from traderos.backtesting.strategies import (
    AlwaysFlatStrategy,
    BuyAndHoldStrategy,
    FixedOrderStrategy,
    Strategy,
)

__all__ = [
    "AccountingError",
    "AlwaysFlatStrategy",
    "BacktestConfigurationError",
    "BacktestEngine",
    "BacktestError",
    "BacktestResult",
    "BacktestConfig",
    "BuyAndHoldBenchmark",
    "BuyAndHoldStrategy",
    "CausalityViolation",
    "CommissionModel",
    "CostConfig",
    "EquitySnapshot",
    "ExecutionPolicy",
    "ExecutionPolicyError",
    "ExecutionReport",
    "ExecutionSimulator",
    "Fill",
    "FixedOrderStrategy",
    "FixedSlippageModel",
    "IdentityCurrencyConverter",
    "InitialPosition",
    "InsufficientCash",
    "IntrabarAmbiguityPolicy",
    "InvalidMarketDataError",
    "InvalidOrderError",
    "InvalidOrderTransition",
    "LedgerEntry",
    "MissingBarPolicy",
    "Order",
    "OrderSide",
    "OrderStatus",
    "OrderTimingError",
    "OrderType",
    "PerformanceMetrics",
    "Portfolio",
    "PositionSnapshot",
    "QuoteOrFixedSpreadModel",
    "SlippageConfig",
    "SpreadConfig",
    "StaticCurrencyConverter",
    "Strategy",
    "StrategyContext",
    "TimeInForce",
    "TradeRecord",
    "ZeroSlippageModel",
    "calculate_metrics",
]
